version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports: 
      - "8081:8080"
  redis-server:
    image: "redis"
  app:
    restart: always
    build: .
    command: npm run dev
    ports:
      - "8080:8080"
    volumes: 
      - .:/usr/app